export const USER_AUTHENTICATED_REQUEST = "USER_AUTHENTICATED_REQUEST";
export const USER_AUTHENTICATED_SUCCESS = "USER_AUTHENTICATED_SUCCESS";
export const USER_AUTHENTICATED_FAILURE = "USER_AUTHENTICATED_FAILURE";
